import { Ovo,Roboto,Barlow_Condensed,Bellefair} from "next/font/google";
import "./globals.css";
import Navigation from "./_components/Navigation";

const ovo = Ovo({
  subsets: ["latin"], 
  weight:["400"]
});

const roboto=Roboto({
  subsets:["latin"],
  display:"swap",
  weight: ["100", "300", "400", "500", "700", "900"],
})

const barlowCondensed=Barlow_Condensed({
  subsets: ["latin"],
  weight: ["300","400", "500", "600", "700"],
  variable: "--font-barlow-condensed",
});

const bellefair=Bellefair({
  subsets:["latin"],
  weight:["400"]
})

export const metadata = {
  title: "space tour",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) { 
  return (
    <html lang="en">
      <body className={`${barlowCondensed.className} ${bellefair.className} overflow-hidden h-screen grid grid-rows-[auto_1fr] min-h-screen antialiased`}>
        <Navigation/>
        <main> 
          {children}
        </main>
      </body>
    </html>
  );
}
